name: Compile et publie les PDF

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  publish:
    uses: IUT-GEII-Annecy/ci-latex-upsti/.github/workflows/build-pdfs.yml@main
    secrets: inherit
